/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:822108:

  if (window!=1) {
    window=1;
  }



} //_CODE_:button1:822108:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:846005:

} //_CODE_:textfield1:846005:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:545251:

} //_CODE_:textfield2:545251:

public void button2_click1(GButton source, GEvent event) { //_CODE_:viewCards:777159:
  if (window!=2) {
    window=2;
  }
  
} //_CODE_:viewCards:777159:

public void button3_click1(GButton source, GEvent event) { //_CODE_:CardCreator:201335:
 
 int addIndex=0;
 addIndex=cards.getTotal();
tFront= new Text(textfield1.getText(),325,125,false);
  tBack= new Text(textfield2.getText(),325,225,false);
 c= new card();
  println("Tfront"+textfield1.getText());
 println("tBack"+textfield2.getText());
 c.addFront(tFront);
 c.addBack(tBack);
 cards.addCard(c);

 
} //_CODE_:CardCreator:201335:

public void button2_click2(GButton source, GEvent event) { //_CODE_:button2:535023:
   cards.switchSide(CardCounter);
} //_CODE_:button2:535023:

public void button3_click2(GButton source, GEvent event) { //_CODE_:button3:813560:
if(CardCounter >0 && CardCounter <= cards.getTotal());
CardCounter++;
} //_CODE_:button3:813560:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:904502:
 if(CardCounter >0 && CardCounter <= cards.getTotal());
 CardCounter--;
} //_CODE_:button4:904502:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 10, 30, 80, 30);
  button1.setText("Create New Card");
  button1.addEventHandler(this, "button1_click1");
  textfield1 = new GTextField(this, 120, 64, 270, 50, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  textfield2 = new GTextField(this, 120, 150, 270, 50, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  viewCards = new GButton(this, 11, 81, 80, 30);
  viewCards.setText("view Cards");
  viewCards.addEventHandler(this, "button2_click1");
  CardCreator = new GButton(this, 392, 228, 80, 30);
  CardCreator.setText("Create");
  CardCreator.addEventHandler(this, "button3_click1");
  button2 = new GButton(this, 224, 400, 80, 30);
  button2.setText("Flip");
  button2.addEventHandler(this, "button2_click2");
  button3 = new GButton(this, 576, 400, 80, 30);
  button3.setText("Next Card");
  button3.addEventHandler(this, "button3_click2");
  button4 = new GButton(this, 464, 400, 80, 30);
  button4.setText("Previous Card");
  button4.addEventHandler(this, "button4_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GTextField textfield1; 
GTextField textfield2; 
GButton viewCards; 
GButton CardCreator; 
GButton button2; 
GButton button3; 
GButton button4; 
